CREATE TABLE `order_form_202311`
(
    `nid`             bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `id`              bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '逻辑主键',
    `order_id`        varchar(50)         NOT NULL DEFAULT '' COMMENT '订单号',
    `ext_order_id`    varchar(50)         NOT NULL DEFAULT '' COMMENT '外部订单号',
    `pid`             bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '对应商品表ID',
    `source`          varchar(30)         NOT NULL DEFAULT '' COMMENT '订单来源',
    `qunar_name`      varchar(40)         NOT NULL DEFAULT '' COMMENT '买方在qunar的账户用户名',
    `buyer_name`      varchar(50)         NOT NULL DEFAULT '' COMMENT '买方姓名',
    `buyer_phone`     varchar(15)         NOT NULL DEFAULT '' COMMENT '联系人手机号',
    `inventory_cnt`   int(10) unsigned    NOT NULL DEFAULT '0' COMMENT '购买库存数量',
    `inventory_price` decimal(8, 2)       NOT NULL DEFAULT '0.00' COMMENT '商品单价',
    `price`           decimal(8, 2)       NOT NULL DEFAULT '0.00' COMMENT '订单金额',
    `express_price`   decimal(8, 2)       NOT NULL DEFAULT '0.00' COMMENT '快递金额',
    `status`          tinyint(4)          NOT NULL DEFAULT '0' COMMENT '订单状态，1未支付、2支付成功、3订单取消',
    `is_invoice`      tinyint(4)          NOT NULL DEFAULT '0' COMMENT '是否需要发票，0不需要 1需要',
    `pay_id`          varchar(50)         NOT NULL DEFAULT '' COMMENT '支付流水号',
    `paid_time`       timestamp           NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '支付完成时间',
    `create_time`     timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`     timestamp           NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '更新时间',
    `discount_price`  decimal(8, 2)       NOT NULL DEFAULT '0.00' COMMENT '优惠总金额',
    `total_price`     decimal(8, 2)       NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
    `parent_order_no` varchar(64)         NOT NULL DEFAULT '' COMMENT '父订单号',
    `buyer_email`     varchar(45)         NOT NULL DEFAULT '' COMMENT '联系人邮件',
    `remark`          varchar(500)        NOT NULL DEFAULT '' COMMENT '订单备注',
    `ticket_time`     timestamp           NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '出票时间',
    `sale_mode`       tinyint(3)          NOT NULL DEFAULT '-1' COMMENT '搭售类型 0，搭售，1，套餐，-1，未知',
    `product_type`    int(10) unsigned    NOT NULL DEFAULT '0' COMMENT '产品类型',
    `exp_code`        varchar(30)         NOT NULL DEFAULT '' COMMENT '价格测试方案code',
    `gift`            tinyint(1)          NOT NULL DEFAULT '0' COMMENT '是否赠品',
    `packing`         tinyint(1)          NOT NULL DEFAULT '0' COMMENT '是否打包商品',
    `voucher_phone`   varchar(30)         NOT NULL DEFAULT '' COMMENT '发券手机号',
    PRIMARY KEY (`nid`),
    UNIQUE KEY `uniq_id` (`id`),
    UNIQUE KEY `uniq_order_id_source_buyer_name_buyer_phone` (`order_id`, `source`, `buyer_name`, `buyer_phone`),
    KEY `idx_pay_id` (`pay_id`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_parent_order_no` (`parent_order_no`),
    KEY `idx_status` (`status`),
    KEY `idx_buyer_name` (`buyer_name`),
    KEY `idx_buyer_phone` (`buyer_phone`),
    KEY `idx_qunar_name_create_time` (`qunar_name`, `create_time`),
    KEY `idx_status_pid_create_time` (`status`, `pid`, `create_time`),
    KEY `idx_product_type_create_time` (`product_type`, `create_time`),
    KEY `idx_pid` (`pid`),
    KEY `idx_ext_order_id` (`ext_order_id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 18436210
  DEFAULT CHARSET = utf8 COMMENT ='订单表'